name: Deploy Vite site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build
        run: |
          # Este comando busca dónde está el package.json y entra ahí
          TARGET_DIR=$(find . -name "package.json" -not -path "*/node_modules/*" -exec dirname {} \;)
          echo "Carpeta encontrada: $TARGET_DIR"
          cd $TARGET_DIR
          npm install
          npm run build
          # Movemos el resultado a una carpeta predecible
          mv dist ../final_dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./final_dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
